#cloud-config
users: # Benutzer: Eine Liste von Benutzerkonten, die erstellt werden sollen
  - name: ubuntu # Benutzername: Der Name des Benutzerkontos
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer: Ermöglicht dem Benutzer, sudo ohne Passwortabfrage zu verwenden
    groups: users, admin # Gruppen: Die Benutzergruppen, denen der Benutzer angehört
    home: /home/ubuntu # Home-Verzeichnis: Das Home-Verzeichnis für den Benutzer
    shell: /bin/bash # Shell: Die Standard-Shell für den Benutzer
    ssh_authorized_keys: # SSH-Schlüssel: Eine Liste von öffentlichen SSH-Schlüsseln, die für den SSH-Zugang autorisiert sind
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDrWe5HIeF6ZtLUeACx1T6OCKKM4h2Os24bLmd7xs00M6hRfYQFzyMMHxNIFdWAHu0aqKDYieWn407HANn5nFqbV4vClJeBl76RdM5v2yZXH5KTf2URd1JG1vkFNgdfb0nHWXXpAJYkELkcPwxgOCB2YFATWuOtDQpCb5J265bH5oDeozdB5+vgfypQ2ttK8h8258NJV/es2/SYzXW89OXuPKphLkb98r8L9FyBZyonZCCkmQjPSV2UKeN44zPUjDdJo1fIE1zusam/JXLZQmY4Rad/UNJE/q5W2XtV8OPXKZtEOmDtqZWwEHm8P8G9RaFnqk6tn1fJl72oBxHbRKr aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDwOUB06MwDY5U9La6NPNFVYoeAFnLJu5fHGS1lR2Wp//jXFlURZjHSF5f3hfgQKw9Tr8Qn8cf2Gf7YHjhwto249aqNburKmBhcLuVoEqvtWlxY1lABS9YBa7xIeDCWBSeB2642yX4vhtW+c99KcSdYrereGnZVUWHfygWi2z4O3L2klA+qmRNchx9PMyjahWB72JOw9WjvOMdYa6sXzKZ7KtPojl6mxCW5RT8BTQgApMg7SWTqFYCysbX+j8P8JaC0sCQX1QpRV3dKI5ujJnPMu8ijfbfcfgS1ZKRVLE5R7ZYOddVgwMj6O2aGbICKaX1CrsaSKsytOiwylxnigrwL aws-key
ssh_pwauth: false # SSH-Passwortauthentifizierung: Deaktiviert die Möglichkeit, sich mit einem Passwort über SSH anzumelden
disable_root: false # Root-Login deaktivieren: Erlaubt oder verbietet den Root-Login
package_update: true # Paketaktualisierung: Aktiviert die Aktualisierung von Paketen beim Start
packages: # Pakete: Eine Liste von Paketen, die beim Start installiert werden sollen
  - curl 
  - wget 
